name: Githab-django-action

on:
  
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        python manage.py test articles
  
  
  build_and_push:
    needs: [run_tests]
    runs-on: ubuntu-latest
    env:
      LOGIN: ${{ secrets.DOCKER_LOGIN }}
      NAME: ${{ secrets.DOCKER_NAME }}
    steps:
    - uses: actions/checkout@master
    - name: Copy directory
      run: cd app/
    - name: Login to docker.io
        # Сначала мы логинимся в docker.io#      
      run:  echo ${{ secrets.DOCKER_PWD }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
    - name: build docker
      run: docker build -t $LOGIN/$NAME:${{ github.sha }} -f Dockerfile .
    - name: watch files
      run: ls -l
    - name: show docker image
      run: docker images
    - name: Change prava
      run: sudo chown -R $USER:$USER .
    - name: Push image to docker.io
          # Пушим образ в registry
      run: docker push $LOGIN/$NAME:${{ github.sha }}

